service:
  golangci-lint-version: 1.42.0

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - copyloopvar
    - staticcheck
    - unconvert
    - unused
    - misspell
    - gocheckcompilerdirectives

linters-settings:
  gofmt:
    simplify: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - unusedwrite

issues:
  exclude:
    - G404
    - 'shadow: declaration of "err" shadows declaration at'
  exclude-dirs:
    - build/
  exclude-files:
     - example.*.go
     - server/manifest.go
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - goconst
        - unparam
        - gosec
    - linters:
      - revive
      - gocritic
      path: "server/bot/logger.go"
    - linters:
      - revive
      text: unused-parameter
    - linters:
      - gosec
      text: G115
