// Copyright (c) 2020-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// Type declarations for react-bootstrap when used as external dependency
declare module 'react-bootstrap' {
    import {ComponentType} from 'react';

    export const Modal: ComponentType<any> & {
        Header: ComponentType<any>;
        Body: ComponentType<any>;
        Footer: ComponentType<any>;
        Title: ComponentType<any>;
        Dialog: ComponentType<any>;
    };
    export const Button: ComponentType<any>;
    export const Form: ComponentType<any>;
    export const FormControl: ComponentType<any>;
    export const FormGroup: ComponentType<any>;
    export const FormLabel: ComponentType<any>;
    export const FormText: ComponentType<any>;
    export const FormCheck: ComponentType<any>;
    export const FormCheckInput: ComponentType<any>;
    export const FormCheckLabel: ComponentType<any>;
    export const FormFile: ComponentType<any>;
    export const FormFileInput: ComponentType<any>;
    export const FormFileLabel: ComponentType<any>;
    export const InputGroup: ComponentType<any>;
    export const InputGroupText: ComponentType<any>;
    export const InputGroupPrepend: ComponentType<any>;
    export const InputGroupAppend: ComponentType<any>;
    export const Dropdown: ComponentType<any>;
    export const DropdownButton: ComponentType<any>;
    export const DropdownToggle: ComponentType<any>;
    export const DropdownMenu: ComponentType<any>;
    export const DropdownItem: ComponentType<any>;
    export const Nav: ComponentType<any>;
    export const NavItem: ComponentType<any>;
    export const NavLink: ComponentType<any>;
    export const NavDropdown: ComponentType<any>;
    export const Navbar: ComponentType<any>;
    export const NavbarBrand: ComponentType<any>;
    export const NavbarToggle: ComponentType<any>;
    export const NavbarCollapse: ComponentType<any>;
    export const NavbarText: ComponentType<any>;
    export const Card: ComponentType<any>;
    export const CardHeader: ComponentType<any>;
    export const CardBody: ComponentType<any>;
    export const CardFooter: ComponentType<any>;
    export const CardTitle: ComponentType<any>;
    export const CardText: ComponentType<any>;
    export const CardImg: ComponentType<any>;
    export const CardImgOverlay: ComponentType<any>;
    export const CardGroup: ComponentType<any>;
    export const CardDeck: ComponentType<any>;
    export const CardColumns: ComponentType<any>;
    export const ListGroup: ComponentType<any>;
    export const ListGroupItem: ComponentType<any>;
    export const Table: ComponentType<any>;
    export const Container: ComponentType<any>;
    export const Row: ComponentType<any>;
    export const Col: ComponentType<any>;
    export const Alert: ComponentType<any>;
    export const Badge: ComponentType<any>;
    export const Breadcrumb: ComponentType<any>;
    export const BreadcrumbItem: ComponentType<any>;
    export const ButtonGroup: ComponentType<any>;
    export const ButtonToolbar: ComponentType<any>;
    export const ToggleButton: ComponentType<any>;
    export const ToggleButtonGroup: ComponentType<any>;
    export const SplitButton: ComponentType<any>;
    export const CloseButton: ComponentType<any>;
    export const Spinner: ComponentType<any>;
    export const ProgressBar: ComponentType<any>;
    export const Carousel: ComponentType<any>;
    export const CarouselItem: ComponentType<any>;
    export const CarouselCaption: ComponentType<any>;
    export const Image: ComponentType<any>;
    export const Figure: ComponentType<any>;
    export const FigureImage: ComponentType<any>;
    export const FigureCaption: ComponentType<any>;
    export const Media: ComponentType<any>;
    export const Jumbotron: ComponentType<any>;
    export const ResponsiveEmbed: ComponentType<any>;
    export const Pagination: ComponentType<any>;
    export const PageItem: ComponentType<any>;
    export const Pager: ComponentType<any>;
    export const Popover: ComponentType<any>;
    export const PopoverHeader: ComponentType<any>;
    export const PopoverBody: ComponentType<any>;
    export const PopoverTitle: ComponentType<any>;
    export const PopoverContent: ComponentType<any>;
    export const Tooltip: ComponentType<any>;
    export const OverlayTrigger: ComponentType<any>;
    export const Overlay: ComponentType<any>;
    export const Fade: ComponentType<any>;
    export const Collapse: ComponentType<any>;
    export const Accordion: ComponentType<any>;
    export const AccordionToggle: ComponentType<any>;
    export const AccordionCollapse: ComponentType<any>;
    export const Tab: ComponentType<any>;
    export const Tabs: ComponentType<any>;
    export const TabContainer: ComponentType<any>;
    export const TabContent: ComponentType<any>;
    export const TabPane: ComponentType<any>;
    export const Toast: ComponentType<any>;
    export const ToastHeader: ComponentType<any>;
    export const ToastBody: ComponentType<any>;
    export const Switch: ComponentType<any>;
    export const ElementChildren: ComponentType<any>;
    export const AbstractNav: ComponentType<any>;
    export const AbstractNavItem: ComponentType<any>;
    export const NavContext: ComponentType<any>;
    export const SelectableContext: ComponentType<any>;
    export const TabContext: ComponentType<any>;
    export const ToggleContext: ComponentType<any>;
    export const ModalContext: ComponentType<any>;
    export const AccordionContext: ComponentType<any>;
    export const NavbarContext: ComponentType<any>;
    export const CardContext: ComponentType<any>;
    export const FormContext: ComponentType<any>;
    export const ThemeProvider: ComponentType<any>;
    export const BootstrapModalManager: ComponentType<any>;
    export const SafeAnchor: ComponentType<any>;
    export const createChainedFunction: (...funcs: any[]) => any;
    export const createWithBsPrefix: (prefix: string) => ComponentType<any>;
    export const divWithClassName: (className: string) => ComponentType<any>;
    export const useWrappedRefWithWarning: (ref: any, componentName: string) => any;
    export const usePopperMarginModifiers: (overlay: any) => any;
    export const transitionEndListener: (element: any, handler: any) => any;
    export const triggerBrowserReflow: (node: any) => any;
}

declare module 'react-bootstrap/esm/OverlayTrigger' {
    export const OverlayTrigger: ComponentType<any>;
}
