// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	incident "github.com/mattermost/mattermost-plugin-incident-response/server/incident"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateIncident provides a mock function with given fields: _a0
func (_m *Service) CreateIncident(_a0 *incident.Incident) (*incident.Incident, error) {
	ret := _m.Called(_a0)

	var r0 *incident.Incident
	if rf, ok := ret.Get(0).(func(*incident.Incident) *incident.Incident); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*incident.Incident)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*incident.Incident) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllIncidents provides a mock function with given fields:
func (_m *Service) GetAllIncidents() ([]incident.Incident, error) {
	ret := _m.Called()

	var r0 []incident.Incident
	if rf, ok := ret.Get(0).(func() []incident.Incident); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]incident.Incident)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIncident provides a mock function with given fields: ID
func (_m *Service) GetIncident(ID string) (*incident.Incident, error) {
	ret := _m.Called(ID)

	var r0 *incident.Incident
	if rf, ok := ret.Get(0).(func(string) *incident.Incident); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*incident.Incident)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
