// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mattermost/mattermost-plugin-playbooks/server/app (interfaces: LicenseChecker)

// Package mock_app is a generated GoMock package.
package mock_app

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockLicenseChecker is a mock of LicenseChecker interface
type MockLicenseChecker struct {
	ctrl     *gomock.Controller
	recorder *MockLicenseCheckerMockRecorder
}

// MockLicenseCheckerMockRecorder is the mock recorder for MockLicenseChecker
type MockLicenseCheckerMockRecorder struct {
	mock *MockLicenseChecker
}

// NewMockLicenseChecker creates a new mock instance
func NewMockLicenseChecker(ctrl *gomock.Controller) *MockLicenseChecker {
	mock := &MockLicenseChecker{ctrl: ctrl}
	mock.recorder = &MockLicenseCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLicenseChecker) EXPECT() *MockLicenseCheckerMockRecorder {
	return m.recorder
}

// ChecklistItemDueDateAllowed mocks base method
func (m *MockLicenseChecker) ChecklistItemDueDateAllowed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChecklistItemDueDateAllowed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ChecklistItemDueDateAllowed indicates an expected call of ChecklistItemDueDateAllowed
func (mr *MockLicenseCheckerMockRecorder) ChecklistItemDueDateAllowed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChecklistItemDueDateAllowed", reflect.TypeOf((*MockLicenseChecker)(nil).ChecklistItemDueDateAllowed))
}

// PlaybookAllowed mocks base method
func (m *MockLicenseChecker) PlaybookAllowed(arg0 bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaybookAllowed", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PlaybookAllowed indicates an expected call of PlaybookAllowed
func (mr *MockLicenseCheckerMockRecorder) PlaybookAllowed(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaybookAllowed", reflect.TypeOf((*MockLicenseChecker)(nil).PlaybookAllowed), arg0)
}

// RetrospectiveAllowed mocks base method
func (m *MockLicenseChecker) RetrospectiveAllowed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrospectiveAllowed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// RetrospectiveAllowed indicates an expected call of RetrospectiveAllowed
func (mr *MockLicenseCheckerMockRecorder) RetrospectiveAllowed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrospectiveAllowed", reflect.TypeOf((*MockLicenseChecker)(nil).RetrospectiveAllowed))
}

// StatsAllowed mocks base method
func (m *MockLicenseChecker) StatsAllowed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatsAllowed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// StatsAllowed indicates an expected call of StatsAllowed
func (mr *MockLicenseCheckerMockRecorder) StatsAllowed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatsAllowed", reflect.TypeOf((*MockLicenseChecker)(nil).StatsAllowed))
}

// TimelineAllowed mocks base method
func (m *MockLicenseChecker) TimelineAllowed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimelineAllowed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// TimelineAllowed indicates an expected call of TimelineAllowed
func (mr *MockLicenseCheckerMockRecorder) TimelineAllowed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimelineAllowed", reflect.TypeOf((*MockLicenseChecker)(nil).TimelineAllowed))
}
