// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mattermost/mattermost-plugin-playbooks/server/app (interfaces: ConditionService)

// Package mock_app is a generated GoMock package.
package mock_app

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	app "github.com/mattermost/mattermost-plugin-playbooks/server/app"
)

// MockConditionService is a mock of ConditionService interface.
type MockConditionService struct {
	ctrl     *gomock.Controller
	recorder *MockConditionServiceMockRecorder
}

// MockConditionServiceMockRecorder is the mock recorder for MockConditionService.
type MockConditionServiceMockRecorder struct {
	mock *MockConditionService
}

// NewMockConditionService creates a new mock instance.
func NewMockConditionService(ctrl *gomock.Controller) *MockConditionService {
	mock := &MockConditionService{ctrl: ctrl}
	mock.recorder = &MockConditionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConditionService) EXPECT() *MockConditionServiceMockRecorder {
	return m.recorder
}

// CopyPlaybookConditionsToPlaybook mocks base method.
func (m *MockConditionService) CopyPlaybookConditionsToPlaybook(arg0, arg1 string, arg2 *app.PropertyCopyResult) (map[string]*app.Condition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyPlaybookConditionsToPlaybook", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]*app.Condition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyPlaybookConditionsToPlaybook indicates an expected call of CopyPlaybookConditionsToPlaybook.
func (mr *MockConditionServiceMockRecorder) CopyPlaybookConditionsToPlaybook(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyPlaybookConditionsToPlaybook", reflect.TypeOf((*MockConditionService)(nil).CopyPlaybookConditionsToPlaybook), arg0, arg1, arg2)
}

// CopyPlaybookConditionsToRun mocks base method.
func (m *MockConditionService) CopyPlaybookConditionsToRun(arg0, arg1 string, arg2 *app.PropertyCopyResult) (map[string]*app.Condition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyPlaybookConditionsToRun", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]*app.Condition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyPlaybookConditionsToRun indicates an expected call of CopyPlaybookConditionsToRun.
func (mr *MockConditionServiceMockRecorder) CopyPlaybookConditionsToRun(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyPlaybookConditionsToRun", reflect.TypeOf((*MockConditionService)(nil).CopyPlaybookConditionsToRun), arg0, arg1, arg2)
}

// CreatePlaybookCondition mocks base method.
func (m *MockConditionService) CreatePlaybookCondition(arg0 string, arg1 app.Condition, arg2 string) (*app.Condition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaybookCondition", arg0, arg1, arg2)
	ret0, _ := ret[0].(*app.Condition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaybookCondition indicates an expected call of CreatePlaybookCondition.
func (mr *MockConditionServiceMockRecorder) CreatePlaybookCondition(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaybookCondition", reflect.TypeOf((*MockConditionService)(nil).CreatePlaybookCondition), arg0, arg1, arg2)
}

// DeletePlaybookCondition mocks base method.
func (m *MockConditionService) DeletePlaybookCondition(arg0, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlaybookCondition", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlaybookCondition indicates an expected call of DeletePlaybookCondition.
func (mr *MockConditionServiceMockRecorder) DeletePlaybookCondition(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlaybookCondition", reflect.TypeOf((*MockConditionService)(nil).DeletePlaybookCondition), arg0, arg1, arg2, arg3)
}

// EvaluateAllConditionsForRun mocks base method.
func (m *MockConditionService) EvaluateAllConditionsForRun(arg0 *app.PlaybookRun) (*app.ConditionEvaluationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateAllConditionsForRun", arg0)
	ret0, _ := ret[0].(*app.ConditionEvaluationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateAllConditionsForRun indicates an expected call of EvaluateAllConditionsForRun.
func (mr *MockConditionServiceMockRecorder) EvaluateAllConditionsForRun(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateAllConditionsForRun", reflect.TypeOf((*MockConditionService)(nil).EvaluateAllConditionsForRun), arg0)
}

// EvaluateConditionsOnValueChanged mocks base method.
func (m *MockConditionService) EvaluateConditionsOnValueChanged(arg0 *app.PlaybookRun, arg1 string) (*app.ConditionEvaluationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateConditionsOnValueChanged", arg0, arg1)
	ret0, _ := ret[0].(*app.ConditionEvaluationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateConditionsOnValueChanged indicates an expected call of EvaluateConditionsOnValueChanged.
func (mr *MockConditionServiceMockRecorder) EvaluateConditionsOnValueChanged(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateConditionsOnValueChanged", reflect.TypeOf((*MockConditionService)(nil).EvaluateConditionsOnValueChanged), arg0, arg1)
}

// GetPlaybookCondition mocks base method.
func (m *MockConditionService) GetPlaybookCondition(arg0, arg1, arg2 string) (*app.Condition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookCondition", arg0, arg1, arg2)
	ret0, _ := ret[0].(*app.Condition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookCondition indicates an expected call of GetPlaybookCondition.
func (mr *MockConditionServiceMockRecorder) GetPlaybookCondition(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookCondition", reflect.TypeOf((*MockConditionService)(nil).GetPlaybookCondition), arg0, arg1, arg2)
}

// GetPlaybookConditions mocks base method.
func (m *MockConditionService) GetPlaybookConditions(arg0, arg1 string, arg2, arg3 int) (*app.GetConditionsResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaybookConditions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*app.GetConditionsResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaybookConditions indicates an expected call of GetPlaybookConditions.
func (mr *MockConditionServiceMockRecorder) GetPlaybookConditions(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaybookConditions", reflect.TypeOf((*MockConditionService)(nil).GetPlaybookConditions), arg0, arg1, arg2, arg3)
}

// GetRunConditions mocks base method.
func (m *MockConditionService) GetRunConditions(arg0, arg1, arg2 string, arg3, arg4 int) (*app.GetConditionsResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunConditions", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*app.GetConditionsResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunConditions indicates an expected call of GetRunConditions.
func (mr *MockConditionServiceMockRecorder) GetRunConditions(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunConditions", reflect.TypeOf((*MockConditionService)(nil).GetRunConditions), arg0, arg1, arg2, arg3, arg4)
}

// UpdatePlaybookCondition mocks base method.
func (m *MockConditionService) UpdatePlaybookCondition(arg0 string, arg1 app.Condition, arg2 string) (*app.Condition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaybookCondition", arg0, arg1, arg2)
	ret0, _ := ret[0].(*app.Condition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlaybookCondition indicates an expected call of UpdatePlaybookCondition.
func (mr *MockConditionServiceMockRecorder) UpdatePlaybookCondition(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaybookCondition", reflect.TypeOf((*MockConditionService)(nil).UpdatePlaybookCondition), arg0, arg1, arg2)
}
