# Copyright 2022 Mattermost, Inc.
name: "e2e-test"
description: This action used to runs cypress e2e integration tests

inputs:
  CYPRESS_serverEdition:
    description: The cypress server edition
    required: true
  SPECS:
    description: The cypress specs to run
    required: true
runs:
  using: "composite"
  steps:
    - name: ci/disable-ALSA
      run: printf "pcm.!default {\n    type plug\n    slave.pcm \"null\"\n}\n" > ~/.asoundrc;
      shell: bash

    - name: ci/restore-postresql
      uses: docker://postgres:10.17
      env:
        TEST_DATABASE_URL: postgres://mmuser:mostest@postgres:5432/mattermost_test
      with:
        entrypoint: ./.github/actions/e2e-test/generate-test-data.sh

    - name: ci/upload-licence
      env:
        MM_SERVICESETTINGS_SITEURL: http://localhost:8065
        MM_ADMIN_USERNAME: sysadmin
        MM_ADMIN_PASSWORD: Sys@dmin-sample1
      run: |
        TOKEN=`curl -i -d '{"login_id":"'${MM_ADMIN_USERNAME}'","password":"'${MM_ADMIN_PASSWORD}'"}' $MM_SERVICESETTINGS_SITEURL/api/v4/users/login | grep Token | cut -d' ' -f2`
        TOKEN=${TOKEN//$'\r'/}
        STATUSCODE=$(curl --retry 3 -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d '{"trialreceive_emails_accepted": true, "terms_accepted": true, "users": 100}' $MM_SERVICESETTINGS_SITEURL/api/v4/trial-license -w "%{http_code}" -o /dev/stderr)
        if test $STATUSCODE -ne 200; then exit 1; fi
      shell: bash

    - name: ci/installing-deps
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      env:
        NODE_ENV: development
      run: |
        cd webapp
        npm install --ignore-scripts --no-save
        cd ../tests-e2e
        npm install --ignore-scripts --no-save

    - name: ci/installing-cypress-deps
      shell: bash
      env:
        NODE_ENV: development
      run: |
        sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
        cd tests-e2e/
        npx cypress install

    - name: ci/install-playbooks
      env:
        MM_SERVICESETTINGS_SITEURL: http://localhost:8065
        MM_ADMIN_USERNAME: sysadmin
        MM_ADMIN_PASSWORD: Sys@dmin-sample1
        MM_SERVICESETTINGS_ENABLEDEVELOPER: "true" ## Build only default since we are testing all arch on lint stage to speed up tests
      run: make deploy CGO_ENABLED=0
      shell: bash

    - name: ci/run-cypress-tests
      env:
        TYPE: NONE
        PULL_REQUEST: ""
        BROWSER: chrome
        HEADLESS: "true"
        DASHBOARD_ENABLE: "false"
        FULL_REPORT: "false"
        MM_SERVICESETTINGS_SITEURL: http://localhost:8065
        MM_ADMIN_USERNAME: sysadmin
        MM_ADMIN_PASSWORD: Sys@dmin-sample1
        CYPRESS_serverEdition: ${{ inputs.CYPRESS_serverEdition }}
        TERM: xterm
      run: |
        cd tests-e2e
        npm run test -- --spec "${{ inputs.SPECS }}"
      shell: bash

    - name: ci/upload-cypress-test-results
      if: always()
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: cypress-test-results
        path: |
          tests-e2e/cypress/results/junit
          tests-e2e/cypress/videos
          tests-e2e/cypress/screenshots
        retention-days: 14 ## No need to keep test results more than 14 days
