DO
$$
BEGIN
    IF NOT EXISTS (
        SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
        WHERE TABLE_NAME = 'IR_ViewedChannel' 
        AND CONSTRAINT_TYPE = 'PRIMARY KEY' 
        AND TABLE_CATALOG = (SELECT CURRENT_DATABASE())
    ) THEN
        ALTER TABLE IR_ViewedChannel ADD PRIMARY KEY (ChannelID, UserID);
	END IF;
END
$$;
