// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	config "github.com/mattermost/mattermost-plugin-incident-response/server/config"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetConfiguration provides a mock function with given fields:
func (_m *Service) GetConfiguration() *config.Configuration {
	ret := _m.Called()

	var r0 *config.Configuration
	if rf, ok := ret.Get(0).(func() *config.Configuration); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Configuration)
		}
	}

	return r0
}

// RegisterConfigChangeListener provides a mock function with given fields: listener
func (_m *Service) RegisterConfigChangeListener(listener func()) string {
	ret := _m.Called(listener)

	var r0 string
	if rf, ok := ret.Get(0).(func(func()) string); ok {
		r0 = rf(listener)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// UnregisterConfigChangeListener provides a mock function with given fields: id
func (_m *Service) UnregisterConfigChangeListener(id string) {
	_m.Called(id)
}

// UpdateConfiguration provides a mock function with given fields: f
func (_m *Service) UpdateConfiguration(f func(*config.Configuration)) error {
	ret := _m.Called(f)

	var r0 error
	if rf, ok := ret.Get(0).(func(func(*config.Configuration)) error); ok {
		r0 = rf(f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
