# Copyright 2022 Mattermost, Inc.
name: "test-with-db"
description: This action used to runs tests with db integration

runs:
  using: "composite"
  steps:
    - name: ci/setup-go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: "${{ env.GO_VERSION }}"
        cache: true

    - name: ci/setup-node
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version-file: ".nvmrc"
        cache: "npm"
        cache-dependency-path: |
          webapp/package-lock.json
          e2e-tests/package-lock.json

    - name: ci/cache-node-modules
      id: cache-node-modules
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: |
          webapp/node_modules
          e2e-tests/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('webapp/package-lock.json') }}-${{ hashFiles('e2e-tests/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules-${{ hashFiles('webapp/package-lock.json') }}-${{ hashFiles('e2e-tests/package-lock.json') }}

    - name: ci/setup-webapp-npm-deps
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      env:
        NODE_ENV: development
      run: |
        cd webapp
        npm install --ignore-scripts --no-save --legacy-peer-deps

    - name: ci/test-db-integration
      shell: bash
      env:
        POSTGRES_USER: mmuser
        POSTGRES_DB: mattermost_test
        MYSQL_ROOT_PASSWORD: mostest
        MYSQL_DATABASE: mattermost_test
        MYSQL_USER: mmuser
        MYSQL_PASSWORD: mostest
        MARIADB_ROOT_PASSWORD: mostest
        MARIADB_DATABASE: mattermost_test
        MARIADB_USER: mmuser
        MARIADB_PASSWORD: mostest
      run: make test-ci

    - name: ci/upload-test-results
      if: always()
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
      with:
        name: test-results-${{ github.workflow }}-${{ github.job }}
        path: report.xml
        retention-days: 5 ## No need to keep test results for more than 5 days
        overwrite: true
