# Copyright 2022 Mattermost, Inc.
name: "test-with-db"
description: This action used to runs tests with db integration

runs:
  using: "composite"
  steps:
    - name: ci/cache-node-modules
      id: cache-node-modules
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          webapp/node_modules
          e2e-tests/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('webapp/package-lock.json') }}-${{ hashFiles('e2e-tests/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules-${{ hashFiles('webapp/package-lock.json') }}-${{ hashFiles('e2e-tests/package-lock.json') }}

    - name: ci/setup-webapp-npm-deps
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      env:
        NODE_ENV: development
      run: |
        cd webapp
        npm install --ignore-scripts --no-save --legacy-peer-deps

    - name: ci/test-db-integration
      shell: bash
      env:
        IS_CI: true
        POSTGRES_USER: mmuser
        POSTGRES_DB: mattermost_test
        MYSQL_ROOT_PASSWORD: mostest
        MYSQL_DATABASE: mattermost_test
        MYSQL_USER: mmuser
        MYSQL_PASSWORD: mostest
        MARIADB_ROOT_PASSWORD: mostest
        MARIADB_DATABASE: mattermost_test
        MARIADB_USER: mmuser
        MARIADB_PASSWORD: mostest
      run: make test

    - name: ci/upload-test-results
      if: always()
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
      with:
        name: ${{ github.job }}-results
        path: |
          report.xml
          client/report.xml
          build/report.xml
        retention-days: 5 ## No need to keep test results for more than 5 days
