# Copyright 2022 Mattermost, Inc.
name: "test-with-db"
description: This action used to runs tests with db integration

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        cache: true
    - name: Setup Node
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version-file: ".nvmrc"
        cache: "npm"
        cache-dependency-path: |
          webapp/package-lock.json
          tests-e2e/package-lock.json
    - name: Install webapp npm deps
      shell: bash
      env:
        NODE_ENV: development
      run: |
        set -e
        cd webapp
        npm install --ignore-scripts --no-save --legacy-peer-deps
    - name: Test db integration
      shell: bash
      env:
        POSTGRES_USER: mmuser
        POSTGRES_DB: mattermost_test
        MYSQL_ROOT_PASSWORD: mostest
        MYSQL_DATABASE: mattermost_test
        MYSQL_USER: mmuser
        MYSQL_PASSWORD: mostest
        MARIADB_ROOT_PASSWORD: mostest
        MARIADB_DATABASE: mattermost_test
        MARIADB_USER: mmuser
        MARIADB_PASSWORD: mostest
      run: |
        set -e
        make test-ci
        mkdir -p server/test-results
        cp report.xml server/test-results
    - name: Pesist test results
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: test-results
        path: server/test-results/
        retention-days: 5 ## No need to keep CI builds more than 5 days
